apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: default
data:
  grafana.ini: |
    [paths]
    provisioning = /etc/grafana/provisioning

    [server]
    domain = localhost
    
    [security]
    admin_user = admin
    admin_password = admin
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    
    [users]
    allow_sign_up = false

  dashboard-providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /etc/grafana/provisioning/dashboards 