apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catvsdog-backend-monitor
  namespace: default
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: catvsdog
      tier: backend
  endpoints:
  - port: http
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catvsdog-frontend-monitor
  namespace: default
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: catvsdog
      tier: frontend
  endpoints:
  - port: http
    interval: 15s 