- name: Deploy Calculator Container
  hosts: local
  become: true
  become_method: sudo
  tasks:
    - name: Pull Docker Image
      command: docker pull mt2024013/catdog

    - name: Stop existing container
      command: docker rm -f catdog_container
      ignore_errors: yes

    - name: Run the Calculator Container in Interactive Mode
      command: docker run -dit --name catdog_container mt2024013/catdog