stages:
  preprocess:
    cmd: python3 ml_part/data_preprocessing.py
    deps:
      - ml_part/data_preprocessing.py
      - ml_part/config.py
    outs:
      - ml_part/data:      # Relative path
          persist: true
  
  train:
    cmd: python3 ml_part/model.py
    deps:
      - ml_part/model.py
      - ml_part/config.py
      - ml_part/data
    outs:
      - ml_part/checkpoints:  # Relative path
          persist: true
    metrics:
      - ml_part/metrics.json:   # Relative path
          cache: false
    plots:
      - ml_part/plots:         # Relative path
          cache: false
