apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catvsdog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: catvsdog.local  # You can use any domain and add to /etc/hosts
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: catvsdog-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catvsdog-frontend-service
            port:
              number: 80 