apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catvsdog-ingress
  namespace: catvsdog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: catvsdog.local  # You can use this with an /etc/hosts entry for local testing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catvsdog-service
            port:
              number: 80 